import {
  Step, bg, music, show, hide, hideAll, say, n, log, menu, label, goto, gotoIf, doo, reveal, widget, ending,
} from "../engine";
import { anyoneHasFullPicture } from "../ledger";

// Packet Runner — Part 1. Ported from Kate Bertash's full script (RTF),
// rebuilt web-native with the "Who Knows What" ledger replacing trace_meter.
//
// Ledger reveals are wired into the beats where each observer actually learns
// something. The interrogation at the end READS the ledger instead of a score.

export const story: Step[] = [
  // ===================================================================
  // THE BAR
  // ===================================================================
  music("track5"),
  bg("divebarnodrink"),
  n(`It's early evening, and you sit at your favorite local trying to unwind after a long day of running packets back and forth across town.`),
  say("Bartender", `In early today I see. The usual?`),
  menu(`"Ah yes... my usual."`, [
    { text: "The Extra Life", to: "drink_extra" },
    { text: "The Luna-tic", to: "drink_luna" },
    { text: "The Saint Vitus", to: "drink_vitus" },
    { text: "Flavored Seltzer", to: "drink_seltzer" },
    { text: "Iced Coffee", to: "drink_coffee" },
  ]),
  label("drink_extra"),
  say("Bartender", `Lemon Juice, Triple Sec, Gin, Dry Vermouth, Galliano... with a hint of something herbal, always a solid choice.`),
  goto("after_menu"),
  label("drink_luna"),
  say("Bartender", `3 Parts Gin, 1 Part Mezcal, Cherry Juice, Muddled with Sugar and Lemon Juice. Picked up this cherry juice from the skyfarm yesterday.`),
  goto("after_menu"),
  label("drink_vitus"),
  say("Bartender", `Rye, Lemon, Lime, Ginger Beer and Galliano, nice way to round out a long day.`),
  goto("after_menu"),
  label("drink_seltzer"),
  say("Bartender", `You got it, I keep these passionfruit ones in the back just for you.`),
  goto("after_menu"),
  label("drink_coffee"),
  doo((s) => { s.flags.drankCoffee = true; }),
  say("Bartender", `I dunno how you can drink coffee after 3pm, keeps me up all night.`),
  say("You", `Eh I'm basically immune to it now, could have a double espresso and lay down for a nap.`),
  goto("after_menu"),

  label("after_menu"),
  bg("divebar"),
  n(`You sip your drink. You like your gig, an easy job for easy money.`),
  n(`With Secure Socket Layer being the norm these days, you never even have to see what's inside the packets you carry back and forth inside your coat pocket.`),
  menu(`"Tell me more about Secure Socket Layer."`, [
    { text: "What was that again?", to: "ssl_explain" },
    { text: "Nah I remember.", to: "after_ssl" },
  ]),
  label("ssl_explain"),
  n(`SSL means that what the user puts in the packet, I can't see. If I tried to open it, it would be scrambled into a mess of numbers. Only the recipient gets the packet contents.`),
  n(`It's like HTTPS, you know, that lock icon you see in your browser? That's SSL/TLS protecting your connection to websites.`),
  goto("after_ssl"),

  label("after_ssl"),
  n(`The tv in the corner crackles as the bartender reaches up to turn the volume up.`),
  show("breakingnews", "center"),
  n(`It's quiet on this part of the grid, has been for a long time since they started cracking down on protests like the one on the screen.`),
  n(`The Authority seized control after the Plague, it was so easy with all of the chaos for them to fill the power vacuum.`),
  n(`So instead you try to focus on what you can still control these days: the next moment, the next day, the next job.`),
  hide("breakingnews"),
  menu(`Your pocket buzzes, it's your tile.`, [
    { text: "Check your tile", to: "after_buzz" },
    { text: "Ignore it", to: "ignore_buzz" },
  ]),
  label("ignore_buzz"),
  n(`Hmm, I have already been out all day, but I am low on credits. Couldn't hurt to check anyway.`),
  goto("after_buzz"),

  label("after_buzz"),
  show("packettracker", "left"),
  say("Tile", `URGENT: Packet Transfer Request, 400 credits`),
  n(`Most packet pickup requests go for a standard 50 credits, maybe 100. But only one person you know pays this much for a packet run on such short notice.`),
  say("You", `Doc, what are you up to this time?`),
  hide("packettracker"),

  // Comms choice (kept from the redesign — the one self-inflicted ledger wound).
  menu(`How do you tell Doc you're on your way?`, [
    {
      text: "Send an encrypted message (like Signal)",
      run: (s) => { s.usedSms = false; },
      to: "after_reply",
    },
    {
      text: "Just fire off a quick SMS",
      run: (s) => {
        s.usedSms = true;
        s.smsTranscript = "You: On my way, be there soon.  ·  Doc: Good, this is urgent. The Archive. Be careful.";
      },
      reveals: [{ who: "carrier", fact: "association", state: "logged" }],
      to: "after_reply",
    },
  ]),
  label("after_reply"),
  gotoIf((s) => s.usedSms, "sms_note"),
  n(`You send a secure, encrypted message. No one in between can read who you're talking to.`),
  goto("leave_bar"),
  label("sms_note"),
  n(`You fire off a plain SMS. Fast and easy, but your carrier just wrote down that you and Doc were talking tonight.`),
  goto("leave_bar"),

  label("leave_bar"),
  bg("black"),
  n(`You pocket your tile, zip up your coat, leave an extra tip for the bartender, and head into the night...`),

  // ===================================================================
  // DOC'S LAB — first visit
  // ===================================================================
  bg("docslab"),
  log(`A log of your visit to this location has been registered by TILECORP.`),
  reveal({ who: "tile", fact: "identity", state: "logged" }),
  n(`You wish you knew how to turn this thing off. It pings every time you so much as breathe on a job.`),
  n(`Where do all these logs even go? And who would ever care to read them?`),
  say("Doc", `Is that you? Hang on a second...`),
  n(`Over the din of the fans you hear a rustling sound from back in the server racks, someone banging around, trying to step over the thousands of cables snaking across the floor.`),
  show("docchar", "left"),
  say("Doc", `Well aren't you a sight for sore eyes! I must say I'm delighted, I was hoping you'd be my courier today.`),
  say("You", `Yeah it's good to see you, and glad to see uh... the lab looking as usual.`),
  say("Doc", `Busy busy busy! Big things happening on the grid!`),
  n(`The old man's eyes shine bright, more wired than usual. Funny, after all these late-night runs you've never once worked out what he's actually a doctor of.`),
  say("Doc", `I have your packet here. Please do handle this with care, won't you?`),
  hide("docchar"),
  show("packetarchive1", "center"),
  n(`Doc hands over the package. It's small and light, a faraday-bag material fastened with a small screen like a tab, a long number punctuated with periods on the screen. It reminds you of a wax seal.`),
  n(`You notice the encryption indicator shows it's using basic SSL. Doc usually uses stronger encryption for sensitive jobs.`),

  // Encryption choice — the meaningful "contents" input to the ledger.
  menu(`What do you do?`, [
    { text: "Ask for end-to-end encryption (like Signal)", to: "enc_e2e" },
    { text: "Suggest TLS (like email services use)", to: "enc_tls" },
    { text: "Accept basic SSL (like old HTTP sites)", to: "enc_ssl" },
  ]),
  label("enc_e2e"),
  show("docchar", "left"),
  say("You", `Hey Doc, this is on basic SSL. For a job this important, shouldn't we use end-to-end encryption, like Signal?`),
  say("Doc", `Ah, you're paying attention! Good. End-to-end is perfect for this, only you and the recipient can decrypt it, not even the services in between.`),
  doo((s) => { s.encryption = "e2e"; }),
  say("Doc", `Let me upgrade this with perfect forward secrecy. Even if someone breaks the key later, they can't read what came before. Each session gets its own key.`),
  reveal({ who: "archive", fact: "contents", state: "warrant" }),
  goto("after_enc"),
  label("enc_tls"),
  show("docchar", "left"),
  say("You", `For 400 credits I'd feel better with stronger encryption. Can we use TLS, like Gmail or Outlook?`),
  say("Doc", `Smart. TLS protects the connection in transit, the same lock icon you see in a browser. Good, but remember: with TLS the service provider can still see your data.`),
  doo((s) => { s.encryption = "tls"; }),
  reveal({ who: "archive", fact: "contents", state: "warrant" }),
  goto("after_enc"),
  label("enc_ssl"),
  show("docchar", "left"),
  say("You", `You know the rules, man. If my IP isn't on the packet, I don't wanna know.`),
  say("Doc", `Fair enough. Just be careful, basic SSL is like those old HTTP sites before HTTPS. Better than nothing, but anyone handling it along the way could read your packet.`),
  doo((s) => { s.encryption = "ssl"; }),
  reveal(
    { who: "archive", fact: "contents", state: "warrant" },
    { who: "isp", fact: "contents", state: "seen" },
  ),
  say("Doc", `Think of it like a postcard instead of a sealed letter, anyone along the way can read it.`),
  goto("after_enc"),

  label("after_enc"),
  hide("docchar"),
  n(`You tuck the packet away in an inside coat pocket.`),
  hide("packetarchive1"),
  show("docchar", "left"),
  say("Doc", `Very special, this one. Good luck to you, my friend, and keep your eyes in the skies!`),
  n(`Eyes in the skies? What does that mean? You shake his hand goodbye and head off into the night.`),
  hideAll(),
  bg("black"),
  n(`If I wanna exit the 8080 block I have to find the Router. He'll get me out of this dump I call home and onto the network.`),

  // ===================================================================
  // THE ROUTER
  // ===================================================================
  bg("docks"),
  music("track1"),
  n(`Early next morning. You squint into the hazy sunlight and spot him at the edge of the docks, waiting on something that isn't you.`),
  n(`Your pocket buzzes again.`),
  log(`A log of your visit to this location has been registered by TILECORP.`),
  reveal({ who: "tile", fact: "identity", state: "logged" }),
  show("router", "right"),
  say("Router", `Hey kid, early morning for ya.`),
  say("You", `Hey you salty sea dog, it's been a minute. I gotta get over to the network, big job today.`),
  say("Router", `Where ya headed this time?`),
  menu(`What do you tell him?`, [
    { text: "The Archive, never been.", to: "router_log" },
    { text: "Why do you need to know?", to: "router_ask" },
  ]),
  label("router_ask"),
  say("Router", `Got logbooks of my own, kid. Every Router keeps record of everything that comes in and goes out of these docks, every site you're headed to see.`),
  say("You", `Bummer. How long do you keep those records?`),
  say("Router", `I clear my logs every month. Most Routers don't clear them at all.`),
  say("You", `Yeesh, good thing I asked...`),
  goto("router_log"),
  label("router_log"),
  reveal({ who: "router", fact: "destination", state: "logged" }),
  say("Router", `So, the Archive. That part of the network is pretty unstable lately.`),
  say("Router", `We've had downtime recently, and it's hard getting travel permits out of 8080 block. I gotta hang on to the few they give me...`),
  label("start_bribe"),
  menu(`How do you get a ticket?`, [
    { text: "Offer him a cut", to: "end_bribe" },
    { text: "Scold him for fishing for a bribe", to: "scold_router" },
  ]),
  label("scold_router"),
  say("You", `Come on man, it's my only way out of here. I should report you to the Port Authority for that.`),
  say("Router", `Hey kid, nobody said anything about anything. If that's how you're gonna be, you can swim.`),
  goto("start_bribe"),
  label("end_bribe"),
  say("You", `I guess it's just the cost of doing business. 50 credits square us up?`),
  say("Router", `Thanks kid, you can give it to me after the job. I know you're good for it.`),
  doo((s) => { s.credits -= 50; }),
  hide("router"),
  bg("networkharbor"),
  n(`The Router's boat pulls into the harbor and you look out at the sun reflecting off the water. You forgot that the Network is actually quite beautiful when it's not filled with teargas clouds.`),
  n(`You walk up the street from the harbor, and it's only a few short blocks to ISP station.`),

  // ===================================================================
  // ISP & DNS
  // ===================================================================
  bg("ispstation"),
  music("track2"),
  n(`The sight is dizzying, platforms that stretch off in what seems like infinite directions, labeled with series of numbers.`),
  say("You", `Ah nuts, I forgot all the trains aren't labeled by domain names. I won't find "The Archive" on any of these transit maps.`),
  say("You", `Now which one of these train lines is the Archive?`),
  n(`You think better of it and walk over to the booth, where a sharply dressed man with an equally pointed smile awaits you.`),
  bg("ticketbooth"),
  say("You", `...DNS?`),
  say("Dennis", `Oh hello there. And yes, it's Dennis if you like.`),
  say("You", `Uh, hi Dennis. Is this where I get tickets?`),
  say("Dennis", `Certainly. And where are we going today?`),
  menu(`What will you tell him?`, [
    { text: "The Archive", to: "dns_log" },
    { text: "Why do you need to know?", to: "dns_ask" },
  ]),
  label("dns_ask"),
  say("Dennis", `Well, in order to give you the ticket to the block you're going to, I have to take that cute little name, "The Archive," and run it through my system to get you to the right IP address.`),
  goto("dns_log"),
  label("dns_log"),
  say("Dennis", `Thank you. The name of the site is all I need to get you the correct IP address.`),
  reveal({ who: "isp", fact: "destination", state: "logged" }),
  n(`He types for a few moments, giving you time to think about how many people you've already had to tell where you're going.`),
  say("Dennis", `Please hold up your tile to receive your transit pass.`),
  log(`Travel record created by ISP. We thank you for your business.`),
  reveal({ who: "tile", fact: "identity", state: "logged" }),
  show("packetarchive1", "center"),
  n(`You notice the packet buzzing in your pocket too, and take it out. The address is changing.`),
  hide("packetarchive1"),
  show("packetarchive2", "center"),
  say("You", `Remind me again, Dennis, how long does ISP keep my travel records?`),
  hide("packetarchive2"),
  say("Dennis", `Oh, we keep those logs indefinitely.`),
  say("You", `Do you share them with anyone else?`),
  say("Dennis", `Hahaha... oh wait, you weren't joking.`),
  say("Dennis", `Yes, we have to share them. If the Authority asks for them, the ISP turns them over.`),
  say("Dennis", `We have records of every site visited on the ISP. Every person, everywhere, forever.`),
  say("You", `Well... that's unnerving.`),
  say("Dennis", `That's business! Have a great trip, and thank you for riding ISP.`),
  bg("black"),
  n(`You step onto your train, thinking the whole way about how often you use the ISP but never stop to think about the records they keep.`),
  say("You", `Internet Service Provider, more like Internet Surveillance Provider.`),
  n(`But before you have a chance to think too long about it, you arrive at your station.`),
  n(`There's an elevator marked Archive Express, and you decide to save some time and take it up to the main floor.`),

  // ===================================================================
  // THE ARCHIVE
  // ===================================================================
  bg("archiveelevator"),
  music("track7"),
  n(`The doors open on the most beautiful building you've seen in a long time. The Archive is one of the oldest sites on the network, and maybe one of the largest.`),
  n(`To find the right recipient in the largest repository of the world's information, you head for the sign that says "Queries."`),
  bg("librarydesk"),
  say("You", `I have a packet for The Archive.`),
  say("Archivist", `Thank you, may I see it?`),
  show("packetarchive1", "center"),
  n(`You hand her the packet, and she inspects it. She waves her tile over it, and the key on her tile matches the key on the package.`),
  hide("packetarchive1"),
  show("packetdecrypting", "center"),
  n(`The buckle pops open, and she looks inside, though you cannot see the contents. This is typical for most deliveries, so you barely notice.`),
  hide("packetdecrypting"),
  n(`Her eyes widen in surprise, and she looks up at you with a curious glance.`),
  menu(`Hmmm.`, [
    { text: "What is this place?", to: "archive_what" },
    { text: "Is something wrong?", to: "end_archive1" },
  ]),
  label("archive_what"),
  say("Archivist", `The Archive is the steward of the world's information. What began as a simple search engine was eventually nationalized and treated as the world's public library.`),
  say("You", `Wow, that's a huge accomplishment, especially with everything that was going on during the pandemic.`),
  say("Archivist", `One of the last great acts of a dying world.`),
  goto("end_archive1"),
  label("end_archive1"),
  say("Archivist", `About this packet, is the sender known to you?`),
  say("You", `Yes, he's an old regular. Bit of a strange man, but he's always been a good customer.`),
  say("Archivist", `A good customer, and a keen one at that. This packet is ordinary, but the sender is someone very extraordinary.`),
  say("You", `You can tell all that from the packet?`),
  say("Archivist", `This packet may be encrypted to you, but because it is addressed to me, I can decrypt it. Inside is a query for the Archive, as all packets that come here are.`),
  say("You", `And you can not only see what's inside, but who sent it?`),
  say("Archivist", `Yes. I can see exactly who sent it, and what they wanted. This question, like all others, will be logged, as will our answer.`),
  reveal(
    { who: "archive", fact: "contents", state: "warrant" },
    { who: "archive", fact: "association", state: "warrant" },
    { who: "archive", fact: "destination", state: "warrant" },
  ),
  say("You", `How long are these logs kept?`),
  say("Archivist", `Your friend is clever, so his requests have a time limit. But most of the time, the Archive simply keeps all our logs, our questions, our askers, our answers, forever.`),
  say("You", `Wow... I keep hearing a lot of things like that today.`),
  say("Archivist", `We didn't used to. But now we're required by law of the Authority.`),
  say("You", `I should have guessed.`),
  say("Archivist", `Regardless, we have a duty to our users, and to your customer, who is awaiting an answer to his query.`),
  bg("librarydeskempty"),
  say("Archivist", `Please wait here while I fetch the user's requested file.`),
  n(`She returns quickly with the packet.`),
  bg("librarydesk"),
  n(`She waves her tile over it and the key is sealed again, a new number appearing on the white screen of its fastener.`),
  show("packetencrypting", "center"),
  say("You", `Thank you.`),
  hide("packetencrypting"),
  n(`You extend your hand to take the packet, but the Archivist pauses.`),
  say("Archivist", `Before you go, there is one more thing I have to tell you. Because of his question, I know what he is planning, and you must promise to carry this message back with the packet. I have to be able to trust you. Do you understand?`),
  n(`There's an urgency in her voice. Couriers get asked to pass along messages all the time, but never with a face like that.`),
  say("You", `I'll do my best.`),
  say("Archivist", `Listen to me carefully, and repeat it just as I say it:`),
  say("Archivist", `Tell the user that the Eyes are coming for the Archive. We will defend our neutrality as long as we can, but when they request our records, our logs, we must comply.`),
  say("Archivist", `Do you understand what that means?`),
  menu(`Hmm.`, [
    { text: "I think I understand...", to: "archive2" },
    { text: "I don't know what neutrality means.", to: "neutrality" },
  ]),
  label("neutrality"),
  say("Archivist", `Net neutrality is the principle that internet service providers, but also services like ourselves, have a duty to enable free and fair access to all content, regardless of the source.`),
  say("Archivist", `That means we don't favor or block information based on where or who it comes from. And that makes us targets for powerful enemies.`),
  goto("archive2"),
  label("archive2"),
  say("Archivist", `You were watched on your path here. For any further journeys, I recommend you take an unwatched path.`),
  say("You", `An unwatched path? What is that? And who is watching me?`),
  say("Archivist", `I can't tell you any more than that. Ask your user. Good luck, and watch your back. Hold up your tile, please.`),
  log(`A record of this transaction has been created. Thank you for visiting the Archive.`),
  reveal({ who: "tile", fact: "identity", state: "logged" }),
  n(`Another log. How many different records of this one search request are there?`),
  bg("backtodoc"),
  music("track9"),
  n(`You turn the Archivist's words over the whole way back. You know who the Authority is, everyone does. But who are the Eyes, and what would they want with a question anyone could ask a public archive?`),
  bg("black"),
  n(`There's only one person who can answer your query, one even the Archive could not, and that's Doc.`),

  // ===================================================================
  // DOC'S LAB — returns, the steganography reveal, the real mission
  // ===================================================================
  bg("docslab"),
  say("You", `Doc, DOC, I need to talk to you. I have your packet.`),
  show("docchar", "left"),
  say("Doc", `My friend, thank you for returning my packet. But is everything alright?`),
  n(`You tell Doc what the Archivist told you, that the Eyes are on the Archive, and that it would be better to take whatever an "unwatched path" is.`),
  say("Doc", `I see.`),
  n(`Doc goes quiet. The tension builds until you burst out:`),
  menu(``, [
    { text: "What is in the packet!?", to: "doc_packet" },
    { text: "Am I in danger?!", to: "doc_danger" },
  ]),
  label("doc_packet"),
  say("Doc", `Now now, if it's something that can be found in a public archive, it couldn't be all that sinister, yes?`),
  goto("doc_stego"),
  label("doc_danger"),
  say("Doc", `Now now, I would never dream of putting you in a position where anything I handed you could be attributed to you.`),
  goto("doc_stego"),
  label("doc_stego"),
  hide("docchar"),
  show("packetdecrypting", "center"),
  n(`Doc slides his tile over the packet.`),
  hide("packetdecrypting"),
  show("packetarchive2", "center"),
  n(`As Doc's IP appears on the screen, it pops open, and he pulls out a small square of cardstock... it looks like a photograph.`),
  hide("packetarchive2"),
  n(`It's a photo of a sunset, soft and golden, setting over the ocean.`),
  say("You", `Just a plain old photograph?`),
  say("Doc", `Sort of. Now watch this.`),
  n(`Doc feeds the photo into a scanner and pulls it up on his screen. You watch over his shoulder.`),
  n(`The pixels begin to peel off row by row, almost as if pulling apart the colors and adding them to a counter rolling upward on the side of the screen.`),
  say("Doc", `This image has been changed slightly so that certain pixels don't show the perfect Red-Green-Blue value they should, compared to the colors next to them.`),
  say("Doc", `If I count the altered pixels, and how much their RGB value was changed, I start to get a series of numbers...`),
  say("You", `So it's a code?`),
  say("Doc", `Yes. Hiding codes inside images, or even sound waves, other media, is called steganography.`),
  say("Doc", `Hidden in plain sight. What better place? Ah, here it comes...`),
  widget("stego_decode", "▦ stego · decode", `The scanner reads the last bit of every pixel. The hidden numbers fall out.`),
  say("You", `Another IP address?`),
  say("Doc", `Right you are, my friend! And there we have it, that is the destination where I'm sending you next.`),
  n(`You take a step back from the desk, alarmed at his suggestion that you go back out where you've just been told someone is watching you.`),
  say("You", `No way, Doc. This already sounds like something I can't get mixed up in. That Archivist wasn't kidding around.`),
  say("Doc", `Don't worry! This time I won't send you via the ISP. I've been saving up and can get you onto the VPN instead.`),
  menu(``, [
    { text: "I have no idea what the VPN is...", to: "vpn_explain" },
    { text: "Yeah I know what a VPN is, but...", to: "endvpn" },
  ]),
  label("vpn_explain"),
  say("Doc", `A Virtual Private Network. It carries your traffic across the public network without showing the people who own that network where you're going.`),
  goto("endvpn"),
  label("endvpn"),
  say("You", `Are you asking me to commit a crime?`),
  say("Doc", `No. The contents are perfectly legal to share. They're just something powerful people would bend the law to bury.`),
  say("You", `Then why hide? I can't get mixed up in politics. It's none of my business.`),
  say("Doc", `I know. You're tired of feeling like nothing you do matters. But this matters, and I'm too old to carry it myself.`),
  say("You", `DOC, I CAN'T. I'm a courier. I move data, I don't get involved.`),
  n(`Doc pauses, realizing he's overwhelmed you. He invites you to sit down for a moment and take a deep breath.`),
  say("Doc", `Then let me tell you why I only ever hire you. Every other courier tried to sell me out, or trick me into sending things unencrypted, or sell my data.`),
  say("Doc", `You never did. You've got your own code, and you keep it.`),
  say("You", `Every user has the right to encryption. That's just basic. Anyone would do...`),
  say("Doc", `NO. No, they would not. Even when they have to encrypt, these days everyone's metadata is for sale. Bit by bit, they're whittling away and selling off the privacy rights we have left.`),
  label("metadatamenu"),
  menu(`hmm...`, [
    { text: "What is metadata?", to: "meta_what" },
    { text: "Who are They? The Eyes?", to: "meta_eyes" },
  ]),
  label("meta_what"),
  say("Doc", `Not the contents of your message, but everything around it that never gets encrypted. Where you went, when, and who you were with.`),
  widget("metadata_profile", "▦ metadata · profile", `Each sealed message still leaks a label. Stack enough, and they have you.`),
  goto("metadatamenu"),
  label("meta_eyes"),
  say("Doc", `Yes. They are the Eyes. They collect all of our information, as much as they can get their hands on, and use it for their own nefarious purposes.`),
  goto("endmetadata"),
  label("endmetadata"),
  n(`Whatever this is, the stakes are clearly bigger than you understand yet. And maybe that's reason enough to keep going.`),
  say("Doc", `And of course, I'll pay. Let's say double the rate of a usual transfer, plus a VPN pass you can use for the rest of the trip.`),
  doo((s) => { s.credits += 800; }),
  n(`There's a twinkle in his eye, a young hacker itching to brag. But he keeps the secret to himself, and you realize you're curious enough to stay.`),
  say("You", `You know me too well, Doc. It's a deal.`),
  say("Doc", `Thank you for trusting me. Trust is the highest currency we have these days. But let's get out your tile and make it official.`),
  hideAll(),

  // ===================================================================
  // THE VPN
  // ===================================================================
  bg("ispstation"),
  n(`Back at ISP station, you look up at the monitors and find your train, ticket in hand. But you'll only be taking it one station...`),
  bg("black"),
  n(`You get off one stop past ISP and try to remember Doc's directions. A small door off the main corridor, he said. You'll know it when you see it.`),
  bg("vpnentrance"),
  say("You", `Well, I suppose that's it then. Very discreet.`),
  n(`You pause to think about what Doc said, that you needed to pay for a pass, or else the "fee" is letting them sell your data.`),
  say("You", `I guess in the end nothing is free.`),
  n(`You pay the man at the door.`),
  bg("vpnstation"),
  n(`Inside, it's just another platform, much like ISP station. Glancing at the map, the VPN even runs to all the same stops. What's the fuss?`),
  show("attendant", "right"),
  say("Station Attendant", `Need help finding something?`),
  n(`A station attendant appears, studying your puzzled face.`),
  say("You", `I just don't understand the difference between this VPN and just using the ISP.`),
  say("Station Attendant", `ISPs keep logs of the sites you visit, and that information can often be requested by the Authority if they have a warrant.`),
  say("Station Attendant", `But here on the VPN, we get you to the same place, we just don't care to keep your logs.`),
  say("You", `So there's a better chance the sites I visit via VPN stay private, just to me.`),
  say("Station Attendant", `You catch on quick. Just remember: a VPN that's free is usually a lot less honest about whether it keeps your logs, or quietly sells them.`),
  say("You", `Yeah. I suppose if something is free, you are the product.`),
  say("Station Attendant", `Now you're catching on. I think your train is coming, but thanks for riding VPN.`),
  reveal({ who: "vpn", fact: "destination", state: "seen" }),
  hide("attendant"),
  n(`You thank her, pat your pocket to be sure the packet's still there, and board.`),
  bg("traininterior"),
  n(`On the train, your tile buzzes the way it always does when you arrive somewhere...`),
  n(`...but looking back, you can see no logs in the history of you having arrived at this IP address. Incredible.`),

  // ===================================================================
  // THE UNIVERSITY — Cecilia
  // ===================================================================
  bg("outsideuniv"),
  n(`Your IP appears to be at a university. Your final destination is a computer science building with a rather distinctive architecture.`),
  n(`You find a keypad outside and press in the last two digits of the address, hitting the call button.`),
  say("Voice", `What do you want?`),
  say("You", `I have a package.`),
  say("Voice", `Wait for the buzzer, then come up to Lab 12G.`),
  bg("computerlab"),
  n(`A large computer lab sits out before you. Somewhere down the darkened hallways you hear other fingers tapping urgently at terminals, a discordant symphony of mechanical keys.`),
  show("eddie", "right"),
  say("Eddie", `Glad you found your way in alright. I know it's a maze in here.`),
  say("You", `I have a package for this address.`),
  show("packetdoc", "center"),
  say("Eddie", `Yes, thank you, I'll go get her!`),
  hide("packetdoc"),
  hide("eddie"),
  n(`The man clambers off. If he wasn't the professor whose name was on the door, you wonder who he might be.`),
  show("cecilia", "right"),
  say("Cecilia", `Thanks, I'd been wondering when this might get here. I'll take that, please.`),
  n(`You shrug and hand over the packet. She slides her tile over it and the numbers begin to roll.`),
  show("packetdecrypting", "center"),
  hide("packetdecrypting"),
  say("You", `So I guess you're Dr. C? Who was that, then?`),
  say("Cecilia", `Oh, that's my intern, Eddie.`),
  say("You", `He looks a little, um... late in his schooling to be an intern.`),
  say("Cecilia", `He worked a whole career in industry, then decided to go back to research. I say if you want to intern, why not! Everyone deserves a chance to try something new at any point in life.`),
  n(`The professor pulls a disk from the packet and pops it into the nearest terminal.`),
  say("Cecilia", `I've been waiting a very long time for this. And if I know Doc... YES. My hunch was correct.`),
  n(`She swings back around in her chair.`),
  say("Cecilia", `Because Doc trusts you, I trust you. So you deserve to know what you're carrying, and why it matters.`),
  say("Cecilia", `Do you know what facial recognition is?`),
  menu(`Facial recognition...`, [
    { text: "Yes, I'm familiar with it.", to: "facial" },
    { text: "No, what is that?", to: "facial" },
  ]),
  label("facial"),
  say("Cecilia", `It's a math problem. Every pixel of your face becomes a number, and the machine compares your numbers to everyone else's.`),
  say("You", `Like the RGB values Doc pulled out of that photo.`),
  say("Cecilia", `Exactly. I gave my life to that problem, right here. I told myself the science was neutral, that ethics were someone else's job.`),
  n(`Her hands tighten into fists.`),
  say("Cecilia", `Then I learned the university had licensed our work to people using it to watch everyone. Without asking me. Without asking anyone.`),
  say("You", `...is that what's in the packet?`),
  say("Cecilia", `It's the proof. The last piece Doc got me. And I know exactly who bought it.`),
  say("You", `Who?`),
  say("Cecilia", `They call themselves the Eyes. And here's the worst part: they aren't the Authority. They're a private contractor the Authority hides behind, so no one can hold them to account.`),
  say("Cecilia", `Doc found me after I went quiet. An old hacker with a guilty conscience, like mine. He taught me we can't undo the harm. But we can hand the public the truth.`),
  say("You", `Wouldn't someone else have built it anyway?`),
  say("Cecilia", `Maybe. I'm not the only one who can multiply matrices. But I might be the one who can help people fight it. Why not me?`),
  say("Cecilia", `So you'll take all of it, my evidence and Doc's findings, to the SecureDrop. And we blow this wide open.`),
  say("Cecilia", `Eddie! EDDIE! Bring me the disk.`),
  show("eddie", "left"),
  say("Eddie", `Here you are, Dr. C. I typed out all the transcripts and loaded them in with the original files.`),
  say("Cecilia", `Thank you, Eddie.`),
  hide("eddie"),
  n(`The terminal lights up as files fly off her disk onto the drive Doc gave her.`),
  reveal({ who: "archive", fact: "contents", state: "warrant" }),
  menu(`hmm`, [
    { text: "What's a SecureDrop?", to: "securedrop" },
    { text: "Blow the lid off of what?", to: "securedrop" },
  ]),
  label("securedrop"),
  say("Cecilia", `I think it's best I don't tell you everything yet, in case you get stopped along the way. Need to leave you with some plausible deniability.`),
  say("Cecilia", `But it's time to send you to the SecureDrop. And we're going to need something even better than the VPN if we're going to make sure you don't get caught.`),
  say("You", `What's more private than the VPN?`),
  n(`The professor smiles at you. And then Eddie walks back over with someone you hadn't seen yet.`),
  show("entrynode", "left"),
  say("Cecilia", `I'd like to introduce you to the Tor Network.`),

  // ===================================================================
  // THE TOR HANDSHAKE
  // ===================================================================
  bg("black"),
  n(`You follow along behind, jogging to keep up, trying to ask questions as you're hustled through back alleys and small streets.`),
  bg("alley"),
  n(`Finally she stops walking and waits next to a door, checking her tile. You put your hands on your knees and try to catch your breath.`),
  show("entrynode", "left"),
  say("You", `So who are you again?`),
  say("Entry Node", `I'm the Entry Node, part of something called Tor. It's how you get around the network without being seen.`),
  say("You", `Isn't that just for crime? Are we doing crime??`),
  say("Entry Node", `No, but I get why you'd ask. Tor just makes sure no single link in the chain knows both where you came from and where you're going.`),
  say("Entry Node", `I picked you up, so I know your address. I hand you to the Middle Node, who never learns where you started. They hand you to the Exit Node, who I never meet. Don't want to.`),
  reveal({ who: "tor", fact: "identity", state: "split" }),
  say("You", `So only the Exit Node knows where I end up.`),
  say("Entry Node", `Exactly. Stop any one of us, and we've each only got a piece. None of us can give up your whole story.`),
  widget("onion_route", "▦ tor · route", `Your tile sketches the handoff. Each node holds only a piece.`),
  say("You", `Why doesn't everyone use this?`),
  say("Entry Node", `It's free. Just a little slow, passing couriers like you hand to hand.`),
  say("Entry Node", `Speaking of which, here they come now!`),
  show("middlenode", "right"),
  say("Middle Node", `Great to see you again, and to meet our newest guest on the Tor network.`),
  say("You", `Thanks. It feels weirdly like a relief to not have to tell everyone where I'm going.`),
  say("Middle Node", `Glad to hear it! Now, I hope this helmet fits, because you'll need to come with me if we're going to get you to the Exit Node before anyone spots us.`),
  reveal({ who: "tor", fact: "destination", state: "split" }),
  say("You", `Spots us?`),
  say("Entry Node", `Look up.`),
  n(`Everywhere around you, attached to every building, traffic light, even the tops of some cars, small cameras.`),
  n(`You'd seen them installing them over the last few years, but didn't think much of it. Like a frog in boiling water, you somehow forgot to notice that now there weren't just a few. They were everywhere.`),
  say("You", `Is that what Doc meant by "eyes in the skies"?`),
  say("Middle Node", `I don't know who Doc is, but they sound like they know what they're talking about.`),
  say("Entry Node", `They used to need our tile logs to know where we'd been. Now the cameras run facial recognition on the footage, so they track anyone without ever asking for a warrant.`),
  say("You", `I always figured I had nothing worth hiding. But...`),
  say("Entry Node", `That's how they sell it. "We only watch criminals." Meanwhile they're hunting people like your friend.`),
  say("Middle Node", `And every face they collect can leak, straight to scammers and crooks looking to extort you.`),
  say("You", `Well, I'm ready to find out what's at the end of this yellow brick road. Let's go see the Wizard.`),
  n(`Travelling Tor's compartmented hops, helmet down, you slip beneath the cameras. They never get a clean look at you.`),
  bg("black"),
  n(`You hop on the back of the Middle Node's motorcycle and spin off into the early morning hours.`),
  n(`It's been a long night, the sun just peeking over the horizon. Your heart is still racing.`),
  bg("streetcorner"),
  n(`You pull off the helmet and hand it back to the Middle Node. They lock the bike and motion for you to follow around the corner.`),
  n(`A man is seated at a coffee shop, sipping a small hot drink out of a minuscule cup. You could really use a coffee right now.`),
  bg("coffeeshop"),
  show("exitnode", "right"),
  say("Exit Node", `Thanks, my friend. I'll take it from here.`),
  say("Middle Node", `Adios, kiddo. Take care of yourself, and of that little package. We believe in you.`),
  n(`You turn around to say thanks, but the Middle Node has already disappeared.`),
  say("Exit Node", `Well, you've had a long day. Let's get you a coffee before I take you to SecureDrop.`),
  hide("exitnode"),
  n(`You walk up to the counter and peruse your options.`),
  show("barista", "left"),
  say("Barista", `Morning! What can I get for you?`),
  menu(`What will you order?`, [
    { text: "Iced Coffee", to: "endcoffee" },
    { text: "Double espresso", to: "endcoffee" },
    { text: "Black coffee", to: "endcoffee" },
    { text: "Black tea", to: "endcoffee" },
    { text: "Cyber Unicorn Rainbow Frappuccino", to: "endcoffee" },
  ]),
  label("endcoffee"),
  hide("barista"),
  show("exitnode", "left"),
  say("Exit Node", `Fair warning, the SecureDrop surprises people. It's hidden in plain sight, at a press outlet anyone could walk past.`),
  say("You", `The last few days have been nothing but surprises.`),
  say("Exit Node", `It's how someone hands documents to journalists without anyone learning who they are. You reach it over Tor, so the drop can't be traced back to you.`),
  say("Exit Node", `Yours goes to Unwired Magazine. If you've had enough coffee, I'll take you there now.`),
  say("You", `Thanks. I think I'm finally ready.`),
  bg("street"),
  n(`You exit the coffee shop and follow the Exit Node at a safe distance. He ducks between crowds pouring out of metro stations, all bustling by on their way to work.`),
  n(`You arrive at a small news stand outside a larger building, the sign for Unwired Magazine hanging over the entrance.`),
  say("Exit Node", `And here is where we depart. Good luck, my friend. Stay safe.`),
  hideAll(),

  // ===================================================================
  // THE SECUREDROP
  // ===================================================================
  bg("newsstand"),
  show("vendor", "right"),
  say("You", `I have a packet. Is... is this really the right place to drop it off?`),
  say("News Vendor", `Indeed it is. I'll just take it right through this window here.`),
  n(`You hand the vendor the package and he slides his tile over it.`),
  show("packetdecrypting", "center"),
  n(`The numbers roll, then stop, popping the latch. You hold your breath.`),
  hide("packetdecrypting"),
  n(`The vendor whistles, and out of nowhere a kid appears, a young teen, who takes the drive inside and sprints into the building.`),
  say("You", `Who was that?`),
  say("News Vendor", `Air gap. Makes sure my tile, which has the data of your dropoff, is never connected to where we'll actually open the decrypted files and send them to our journalists in the newsroom.`),
  say("You", `That's a lot of precaution for such a little package.`),
  say("News Vendor", `Best precaution we've got. Encryption, Tor, SecureDrop, the air gap. Without safe ways to share what you brought us, our rights would only be theory.`),
  say("You", `I'm starting to understand what you mean. Thanks.`),
  say("News Vendor", `Remember, kid: you don't have to tell them anything. If they want it, make them go and get it.`),
  say("You", `What does that mean?`),
  say("News Vendor", `I really hope you don't need to find out.`),
  hide("vendor"),
  bg("street"),
  n(`You puzzle over the vendor's words. Your mind is still reeling from the night you've had, and you still don't even know what was really in those packages.`),
  n(`You're so distracted by your own thoughts that you don't even notice the two large uniformed officers coming up behind you.`),
  show("officer1", "left"),
  say("Authority Officer", `That's them.`),
  n(`You turn around only to see a bag go over your head, and feel two strong arms grab you and hustle you off down an alley.`),
  bg("black"),
  say("You", `Where are you taking me?! What is this!`),

  // ===================================================================
  // THE INTERROGATION — reads the ledger
  // ===================================================================
  bg("interrogation"),
  n(`The bag comes off your head and you see you're in an interrogation room.`),
  say("You", `Where am I?`),
  show("officer1", "left"),
  say("Authority Officer", `You were carrying a packet of interest to the Authority. If you want to get out of here, you'll unlock your tile and let us download your logs.`),
  say("You", `I'm pretty sure I don't have to do that. I'm a courier, I carry a lot of packages. It's none of my business.`),
  show("officer2", "right"),
  say("Other Authority Officer", `We saw you at Simon "Doc" Warner's lab two nights ago.`),
  say("You", `If you want to know anything about that, you'll have to ask him.`),
  say("Authority Officer", `We already did.`),

  // The Archive holds the record — but only under warrant.
  hideAll(),
  bg("librarydesk"),
  say("Archivist", `If you want any of our retained search records, you'll need a warrant.`),
  say("Authority Officer", `Yes. I think you'll find all the information we want is right here.`),
  say("Archivist", `We have Dr. Warner's search record, and the resulting sunset photo. I think you already know what that looks like, though, don't you.`),
  bg("interrogation"),
  show("officer1", "left"),
  show("officer2", "right"),
  say("Authority Officer", `Simon Warner thinks he's very clever, or he wouldn't have chosen you. But we know you took the VPN for the next package. Where were you going?`),
  say("You", `I told you, I'm not telling you anything. If you're that sure, why don't you just ask the VPN where I went?`),

  // The VPN keeps no destination logs (it only ever "saw", never "logged").
  hideAll(),
  bg("vpnstation"),
  show("attendant", "left"),
  say("Station Attendant", `You know I need a warrant before I'm even allowed to talk to you.`),
  say("Other Authority Officer", `I think you'll find everything here checks out.`),
  say("Station Attendant", `We have the log for the packet's arrival, but you know as well as I do that we don't keep destination logs.`),
  say("Other Authority Officer", `One way or the other, we'll find out where that packet went.`),
  say("Station Attendant", `And if you do, it won't be from me. Good luck.`),
  hide("attendant"),
  bg("interrogation"),
  show("officer1", "left"),
  show("officer2", "right"),

  // The carrier flashback — only if you sent that SMS.
  gotoIf((s) => !s.usedSms, "after_sms_flashback"),
  say("Authority Officer", `We do have one thing. A transcript, from your carrier.`),
  say("Other Authority Officer", `"You: On my way, be there soon.  ·  Doc: Good, this is urgent. The Archive. Be careful."`),
  say("Other Authority Officer", `An unencrypted SMS, logged by your carrier. We know you and Warner were talking that night.`),
  label("after_sms_flashback"),

  say("You", `I have a feeling if your warrants were going the way you'd like, I wouldn't be in here. So say what you think you want from me, or let me go.`),

  // Tor — entry node only ever had a fragment.
  say("Authority Officer", `The ISP told us you were in touch with the Tor Network. We contacted the entry node. She said she had no idea where you were going, or what you were carrying.`),
  say("You", `And I don't know either, you know that. It could be an order for glow-in-the-dark boxer briefs, or a question like "is a pony a small horse?"`),
  say("You", `Not everyone wants you jerks snooping around in their underwear drawer.`),
  say("Other Authority Officer", `Some people's underwear drawers are full of crime.`),
  say("You", `Then if I've committed a crime, charge me with something. Because I can't tell you what I don't know. And I'm not saying another thing until I have an attorney present.`),
  n(`Your heart is pounding. You can't believe your own courage.`),

  // The verdict: read the ledger.
  gotoIf((s) => anyoneHasFullPicture(s.ledger), "verdict_detained"),
  goto("verdict_released"),

  label("verdict_released"),
  n(`You watch them realize what you already suspected: no single one of the people who watched you tonight holds your whole story. The Archive needs a warrant. The VPN kept no destination. Tor only ever held you in fragments.`),
  say("Authority Officer", `Fine. But we're watching you. Slip up, and we'll be back.`),
  goto("released_out"),

  label("verdict_detained"),
  n(`But the officers are smiling. Somewhere along the way, you let one of them collect the whole picture, who you are, where you went, what you carried, and who you carried it for. That's all the case they need.`),
  say("Other Authority Officer", `Actually... we have everything we need right here. You're under arrest.`),
  bg("black"),
  n(`The cell door closes. The packet made it to the press, but they made an example of the courier who carried it.`),
  say("News Vendor", `(somewhere, a voice you remember) "You don't have to tell them anything. If they want it, make them go and get it." Next time, maybe leave fewer pieces lying around.`),
  goto("ending_card"),

  label("released_out"),
  bg("black"),
  n(`It's been an exhausting few days. You collect your belongings, rub your wrists where the cuffs were digging in, and step out into the street.`),

  // ===================================================================
  // THE NEWS BREAKS
  // ===================================================================
  bg("timessquare"),
  n(`The sunlight is bright. It takes your eyes a moment to adjust to all the commotion on the tv screens up all over the center square.`),
  show("breakingnews", "center"),
  say("Newscaster", `Breaking news: Unwired Magazine has published a whistleblower report that the Authority secretly hired a contractor, Eisenhower Defense Solutions, to run dragnet surveillance on citizens. They call it the Eyes Project.`),
  n(`Your mouth hangs open. That can't be... is that what you were carrying?`),
  say("Newscaster", `The Eyes bought camera footage from DoorSpy Solutions and a facial recognition algorithm from EIT University, building the largest face database in history. Anonymous sources exposed the contract using public records requests.`),
  n(`Every screen blares the same story. People stop on the sidewalks to watch.`),
  say("Newscaster", `The same source leaked the algorithm itself to CodeHub, urging coders everywhere to tear it apart. Senate leaders have opened an investigation into the Authority outsourcing surveillance it could never run within the law.`),
  hide("breakingnews"),
  bg("daystreet"),
  n(`You walk home, mind reeling at your own small part in dragging the truth into the light.`),
  n(`Just one person, who never used to care what happened to their own data. Funny how that goes. I guess we all have a part to play, if we choose it.`),

  // ===================================================================
  // BACK AT THE BAR
  // ===================================================================
  bg("divebarnodrink"),
  n(`The bartender stands in the corner, staring at the news on the screen. As you walk in, he gestures at a seat.`),
  say("Bartender", `Missed you these last few days. What'll it be?`),
  menu(`Order a drink.`, [
    { text: "Ah yes... my usual.", to: "bar2_after" },
    { text: "The Extra Life", to: "bar2_late" },
    { text: "The Luna-tic", to: "bar2_late" },
    { text: "The Saint Vitus", to: "bar2_late" },
    { text: "Flavored Seltzer", to: "bar2_after" },
  ]),
  label("bar2_late"),
  say("Bartender", `Quite the order for this time of day. Late night?`),
  goto("bar2_after"),
  label("bar2_after"),
  bg("divebar"),
  n(`You're about to tell the bartender your story, when suddenly your pocket buzzes.`),
  show("tileblank", "left"),
  n(`It's not a packet request. It's a direct message from Doc.`),
  hide("tileblank"),
  say("Doc", `Thank you for delivering my packet. I'm always so impressed by your quality of service.`),
  say("Doc", `I think, however, that for this next one it's crucial we discuss your rate and the details in person. After all, I owe you a handshake for your last job well done.`),
  say("Doc", `One thing I can tell you on this channel: your last job just scratched the surface. If you're eager to find out more, meet me tonight.`),
  say("Doc", `Oh, and your current drink is on me. See you soon.`),
  n(`The bartender looks up from the cashier console and gives you a thumbs up.`),
  say("You", `Doc, I never have any idea how you do it. But you know what? Let's find out.`),
  bg("black"),
  n(`You finish your drink, wave goodbye to the bartender, and head off to your next, and maybe most interesting, packet pickup yet.`),

  label("ending_card"),
  bg("part1card"),
  n(`Thank you for playing Packet Runner, Part 1. This game is by Kate Bertash.`),
  n(`Open your tile (top-right) to see the full "Who Knows What" ledger from your run, proof of who learned what, and why no one held the whole story.`),
  n(`If you'd like to keep up with progress and release news, follow @katerosebee, or check out the #PacketRunner hashtag. See you on the network...`),
  ending("released"),
];
